name: brew test-bot
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:  # Added to allow manual triggering from the main workflow
    inputs:
      head_sha:  # Input for the PRâ€™s head SHA
        description: 'Head SHA of the PR to test'
        required: true
jobs:
  test-bot:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Intel builds
          - os: macos-13
            arch: x86_64
          - os: macos-14
            arch: x86_64
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60  # Increased timeout for ARM builds
    steps:
      - name: Checkout PR commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.head_sha }}

      - name: Debug head_sha
        run: echo "head_sha=${{ github.event.inputs.head_sha }}"


      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-${{ matrix.arch }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.arch }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - run: brew test-bot --only-tap-syntax

      - run: brew test-bot --only-formulae
        if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
        env:
          HOMEBREW_ARCH: ${{ matrix.arch }}
          GITHUB_SHA: ${{ github.event.inputs.head_sha }}

      - name: Upload bottles as artifact
        if: always() && (github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch')
        uses: actions/upload-artifact@v4
        with:
          name: bottles_${{ matrix.os }}_${{ matrix.arch }}
          path: '*.bottle.*'
